### ISSUE TITLE
Object -Detection Results v_1

### ISSUE THREAD

**Issue by Perri-Woodard** [sunny-day-flooding-project/Object-Detection#1]
Here are the resulting object counts after running through the sample images used to test the first iteration of the object detection script. The script was run on a sample of 40 test images, 37 of which contained flooded imagery and 3 of which were pulled a few days prior to the flood events in order to test non-flooded imagery. Objects attempted to detect include cars, trucks, motorcycles, bikes, and people. 

A summary of these results can be found in the spreadsheet object detection results_v1. The plotted data collected from the spreadsheet  object_counts can be found on the plot tab. 

So far, some problems include issues with missing or misidentifying vehicles or people in background, and issues with counting objects as people that are not people. Ideally, future iterations of the code will have the capability to isolate the roadway, as well as output the images with bounding boxes drawn in order to confirm what each counted object is being identified as. Overall goal is to be able to sort images by flood event, and then quantify objects by flood. 

Files: 
[object detection results_v1.xlsx](https://github.com/user-attachments/files/17600082/object.detection.results_v1.xlsx)
[object_counts.csv](https://github.com/user-attachments/files/17600086/object_counts.csv)

**Comment by ebgoldstein** [comment]
superseded by #3
