### ISSUE TITLE
bounding boxes

### ISSUE THREAD

**Issue by ebgoldstein** [sunny-day-flooding-project/Object-Detection#2]
modify the code to be able to export bounding box location + class.. so that this info can be overlain on the image.

**Comment by Perri-Woodard** [comment]
Hi Evan, 

I have updated the code to include exporting a csv with the bounding box location + class, as well added functionality to output images with the bounding boxes drawn and class labels added. Let me know if this seems sufficient/ if I should make any edits! Also, let me know if there is a time next week later in the wee when you would be available to discuss next steps. Thanks!

**Comment by ebgoldstein** [comment]
Awesome! Can you post some results? I recommend taking all the pics you had in the slideshow and posting those with. Oundjng boxes/classes to see what is going on... also- I recommend looking through a bunch of images just to see for yourself if the model is/is not working ...

And Post some pics here in this thread!

**Comment by Perri-Woodard** [comment]
After looking through some of the images, there are a couple of general takeaways I have: 
- Occasional identification of raindrops or water shadows as people occur
-  Counts boat in the high ground as a car a couple of times
-  Double counts trucks as cars (or motorcycles) if the vehicle is being obstructed by something
- Counts shed in the back as car or truck, or something in the house is being counted as something
- Will count reflections in water as people, even if it is not a person's reflection
- Will occasionally count people in vehicles 
- Counts random objects that are slender in nature as people: equipment, stop signs, poles, fire hydrants, cones, etc. 
- Occasionally counts random items off to the side of the images as cars or trucks. 

In general, the model works okay. It definitely has some issues with identifying items that are not in the foreground or are off to the side, or double counting parts of one vehicle as two items. I will post some of these examples below!

**Comment by Perri-Woodard** [comment]
Raindrop as a person: 
![CAM_CB_01_20230830122422_event3](https://github.com/user-attachments/assets/f6d480d6-b319-4623-8a41-f2909dab59cb)

**Comment by Perri-Woodard** [comment]
Here is a link to the updated slideshow with bounding boxes and classes: [Object_Detection V1 Results Discussion- with bounding boxes](https://docs.google.com/presentation/d/1tuLn7RKgTPfimyYADg7X2TJXnmkOGFfwh1_KyUpVnKg/edit#slide=id.g311077f7c0b_0_151)

**Comment by ebgoldstein** [comment]
awesome - those slides are great @Perri-Woodard . 

cc: @anardek - this is an good follow up from last week. 

I'm closing this issue, and opening a new one re: labeling data and retraining the model
